// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnhMk7mDXjYL2zeWw3dnFfCyMBxdfmg-8',
    appId: '1:338946202162:web:9f3523ee6dc89db66e3a2b',
    messagingSenderId: '338946202162',
    projectId: 'quiz-app-cbb66',
    authDomain: 'quiz-app-cbb66.firebaseapp.com',
    storageBucket: 'quiz-app-cbb66.firebasestorage.app',
    measurementId: 'G-LSN2WXBN82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMcb8a5QSB9c3-asV6-S762x6sYZPwoaQ',
    appId: '1:338946202162:android:7898ba69d4b07d1e6e3a2b',
    messagingSenderId: '338946202162',
    projectId: 'quiz-app-cbb66',
    storageBucket: 'quiz-app-cbb66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPGKFJVg88CzjRua43CLIS0cCl04cCmiQ',
    appId: '1:338946202162:ios:f8e4b5c674abff906e3a2b',
    messagingSenderId: '338946202162',
    projectId: 'quiz-app-cbb66',
    storageBucket: 'quiz-app-cbb66.firebasestorage.app',
    iosBundleId: 'com.example.quizGeneratorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPGKFJVg88CzjRua43CLIS0cCl04cCmiQ',
    appId: '1:338946202162:ios:f8e4b5c674abff906e3a2b',
    messagingSenderId: '338946202162',
    projectId: 'quiz-app-cbb66',
    storageBucket: 'quiz-app-cbb66.firebasestorage.app',
    iosBundleId: 'com.example.quizGeneratorApp',
  );
}
